version: '3.8'
services:
  mongodb:
    image: "mongodb:latest"
    restart: always
    volumes:
      - $HOME/Blakc_BackEnd
    ports:
      - "27017:27017"
    networks:
        - Blakc_BackEnd

  Blakc_BackEnd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - mongodb=True
    volumes:
      - $HOME/Blakc_BackEnd
    ports:
     - "8000:8000"
    networks:
      - Blakc_BackEnd
    depends_on:
      - mongodb
    links:
      - "mongodb"
networks:
  Blakc_BackEnd: